version: "3.8"

services:
  ratel-client:
    build:
      context: .
      args:
        RATEL_SERVER_HOST: ${RATEL_SERVER_HOST:-ratel-be.youdomain.com}
        RATEL_SERVER_PORT: ${RATEL_SERVER_PORT:-80}
        RATEL_SERVER_NAME: ${RATEL_SERVER_NAME:-Nico}
        RATEL_SERVER_VERSION: ${RATEL_SERVER_VERSION:-v1.3.0}
        RATEL_IS_DEVELOPMENT: ${RATEL_IS_DEVELOPMENT:-false}
    container_name: ratel-client-dev
    environment:
      - RATEL_SERVER_HOST=${RATEL_SERVER_HOST:-ratel-be.youdomain.com}
      - RATEL_SERVER_PORT=${RATEL_SERVER_PORT:-80}
      - RATEL_SERVER_NAME=${RATEL_SERVER_NAME:-Nico}
      - RATEL_SERVER_VERSION=${RATEL_SERVER_VERSION:-v1.3.0}
      - RATEL_IS_DEVELOPMENT=${RATEL_IS_DEVELOPMENT:-false}
    ports:
      - "8889:80"
    volumes:
      - nginx-logs:/var/log/nginx
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ratel-network

volumes:
  nginx-logs:
    driver: local

networks:
  ratel-network:
    driver: bridge
